exclude: "docs/sql.md|README.md"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: no-commit-to-branch
        args: [--branch, master]
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.1
    hooks:
      - id: prettier
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.32.2
    hooks:
      - id: markdownlint

  - repo: https://github.com/SimpleDataLabsInc/pre-commit-hooks
    rev: 2ef30b1a4c6c3f4cee045a1b576ecd58b160d8a3
    hooks:
      - id: check-docusaurus-frontmatter
        args: ["-rtitle", "-rid", "-rdescription", "-rtags"]
      - id: commit-message-reuse
      - id: word-veto
        args:
          [
            --badwords,
            "spark:Spark,dataframe:DataFrame,Dataframe:DataFrame,DataBricks:Databricks,delta:Delta,python:Python,scala:Scala,vaccum:vacuum,Vaccum:Vacuum,partion:partition,airflow:Airflow",
          ]
