exclude: "docs/index.md|README.md"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: no-commit-to-branch
        args: [--branch, master]
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.32.1
    hooks:
      - id: markdownlint

  - repo: https://github.com/SimpleDataLabsInc/pre-commit-hooks
    rev: 0a5662867ad7f4d2e5df0863c67ce12f0cf13263
    hooks:
      - id: check-docusaurus-frontmatter
        args: ["-rtitle", "-rid", "-rdescription", "-rtags"]
      - id: commit-message-reuse
      - id: word-veto
        args:
          [
            --badwords,
            "spark:Spark,dataframe:DataFrame,Dataframe:DataFrame,json:JSON,gem:Gem,prophecy:Prophecy,pipeline:Pipeline,fabric:Fabric,GIT:Git,git:Git,databricks:Databricks,DataBricks:Databricks,delta:Delta,fabric:Fabric,dataset:Dataset,&:and,sql:SQL,python:Python,scala:Scala,vaccum:vacuum,Vaccum:Vacuum,partion:partition,job:Job,api:API",
          ]
