/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // defaultSidebar: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually
  mySidebar: [
    "index",
    {
      type: "category",
      label: "Getting started",
      link: { type: "doc", id: "getting-started/getting-started" },
      items: [
        {
          type: "category",
          label: "Concepts",
          items: [
            "getting-started/concepts/Fabric",
            {
              type: "category",
              label: "Projects",
              link: {
                type: "doc",
                id: "getting-started/concepts/project/projects",
              },
              items: ["getting-started/concepts/project/project-editor"],
            },
            "getting-started/concepts/templates",
            "getting-started/concepts/pipelines",
            "getting-started/concepts/gems",
          ],
        },
        {
          type: "category",
          label: "Quick starts",
          link: {
            type: "doc",
            id: "getting-started/quick-starts/quick-starts",
          },
          items: [
            "getting-started/quick-starts/analysts-qs",
            "getting-started/quick-starts/engineers-qs",
            "getting-started/quick-starts/databricks-partner-connect",
          ],
        },
        {
          type: "category",
          label: "Tutorials",
          link: {
            type: "doc",
            id: "getting-started/tutorials/tutorials",
          },
          items: [
            "getting-started/tutorials/sql-with-prophecy",
            "getting-started/tutorials/spark-with-databricks",
            "getting-started/tutorials/sql-with-snowflake",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Copilot",
      link: { type: "doc", id: "copilot/copilot" },
      items: [{ type: "autogenerated", dirName: "copilot" }],
    },
    {
      type: "category",
      label: "Release notes",
      link: { type: "doc", id: "release_notes/release_notes" },
      items: [{ type: "autogenerated", dirName: "release_notes" }],
    },
    {
      type: "html",
      value: '<span class="sidebar-divider" />',
    },

    ///------------------ ANALYSTS -------------------------///
    {
      type: "html",
      className: "sidebar-title",
      value: "Analysts",
      defaultStyle: true,
    },
    {
      type: "category",
      label: "Pipeline development",
      link: { type: "doc", id: "analysts/development/development" },
      items: [
        {
          type: "category",
          label: "Pipelines",
          link: { type: "doc", id: "analysts/development/pipelines/pipelines" },
          items: [
            "analysts/development/pipelines/execution",
            "analysts/development/pipelines/pipeline-params",
            "analysts/development/pipelines/data-types",
          ],
        },
        {
          type: "category",
          label: "Gems",
          link: { type: "doc", id: "analysts/development/gems/gems" },
          items: [
            {
              type: "category",
              label: "Source and Target",
              link: {
                type: "doc",
                id: "analysts/development/gems/source-target/source-target",
              },
              items: [
                {
                  type: "category",
                  label: "Tables (Warehouse)",
                  items: [
                    "analysts/development/gems/source-target/table/databricks",
                    "analysts/development/gems/source-target/table/upload-files",
                  ],
                },
                {
                  type: "category",
                  label: "Tables (External systems)",
                  items: [
                    "analysts/development/gems/source-target/external-table/databricks",
                    "analysts/development/gems/source-target/external-table/snowflake",
                    "analysts/development/gems/source-target/external-table/mssql",
                    "analysts/development/gems/source-target/external-table/mongodb",
                    "analysts/development/gems/source-target/external-table/oracle",
                    "analysts/development/gems/source-target/external-table/redshift",
                  ],
                },
                {
                  type: "category",
                  label: "File types",
                  link: {
                    type: "doc",
                    id: "analysts/development/gems/source-target/file/file-types",
                  },
                  items: [
                    "analysts/development/gems/source-target/file/csv",
                    "analysts/development/gems/source-target/file/excel",
                    "analysts/development/gems/source-target/file/json",
                    "analysts/development/gems/source-target/file/parquet",
                    "analysts/development/gems/source-target/file/xml",
                    "analysts/development/gems/source-target/file/text",
                  ],
                },
                {
                  type: "category",
                  label: "Troubleshooting",
                  items: [
                    "analysts/development/gems/source-target/troubleshooting/multi-source-table",
                  ],
                },
              ],
            },
            {
              type: "category",
              label: "Transform",
              items: [
                "analysts/development/gems/transform/aggregate",
                "analysts/development/gems/transform/dynamic-select",
                "analysts/development/gems/transform/fuzzy-match",
                "analysts/development/gems/transform/pivot",
                "analysts/development/gems/transform/transpose",
                "analysts/development/gems/transform/window",
              ],
            },
            {
              type: "category",
              label: "Prepare",
              items: [
                "analysts/development/gems/prepare/data-cleansing",
                "analysts/development/gems/prepare/deduplicate",
                "analysts/development/gems/prepare/filter",
                "analysts/development/gems/prepare/flatten-schema",
                "analysts/development/gems/prepare/limit",
                "analysts/development/gems/prepare/multi-column-rename",
                "analysts/development/gems/prepare/multi-column-edit",
                "analysts/development/gems/prepare/order-by",
                "analysts/development/gems/prepare/record-id",
                "analysts/development/gems/prepare/reformat",
              ],
            },
            {
              type: "category",
              label: "Join",
              items: [
                "analysts/development/gems/join-split/join",
                "analysts/development/gems/join-split/union",
                "analysts/development/gems/join-split/union-by-name",
                "analysts/development/gems/join-split/intersect",
                "analysts/development/gems/join-split/except",
                "analysts/development/gems/join-split/dynamic-replace",
              ],
            },
            {
              type: "category",
              label: "Spatial",
              items: [
                "analysts/development/gems/spatial/create-point",
                "analysts/development/gems/spatial/distance",
              ],
            },
            {
              type: "category",
              label: "Parse",
              items: [
                "analysts/development/gems/parse/json-parse",
                "analysts/development/gems/parse/xml-parse",
                "analysts/development/gems/parse/text-to-column",
              ],
            },
            {
              type: "category",
              label: "Report",
              items: [
                "analysts/development/gems/report/email",
                "analysts/development/gems/report/power-bi",
                "analysts/development/gems/report/tableau",
              ],
            },
            "analysts/development/gems/subgraph/subgraph",
            {
              type: "category",
              label: "Custom",
              items: [
                "analysts/development/gems/custom/sql-statement",
                "analysts/development/gems/custom/rest-api",
                "analysts/development/gems/custom/macro",
                "analysts/development/gems/custom/script",
              ],
            },
            {
              type: "category",
              label: "Visual expressions",
              link: {
                type: "doc",
                id: "analysts/development/gems/visual-expression-builder/visual-expression-builder",
              },
              items: [
                "analysts/development/gems/visual-expression-builder/visual-expression-builder-reference",
                "analysts/development/gems/visual-expression-builder/use-the-expression-builder",
                "analysts/development/gems/visual-expression-builder/variant-data-type",
              ],
            },
          ],
        },

        {
          type: "category",
          label: "Agents and AI",
          link: {
            type: "doc",
            id: "analysts/development/ai-agent/ai-features",
          },
          items: [
            {
              type: "category",
              label: "Agent chat",
              link: {
                type: "doc",
                id: "analysts/development/ai-agent/ai-chat",
              },
              items: [
                "analysts/development/ai-agent/ai-explore",
                "analysts/development/ai-agent/ai-transform",
              ],
            },
            "analysts/development/copilot/expression-generation",
            "analysts/development/copilot/auto-documentation",
            "analysts/development/copilot/generate-fix",
          ],
        },
        "analysts/development/connections",
        {
          type: "category",
          label: "Data exploration",
          link: {
            type: "doc",
            id: "analysts/development/data-explorer/data-explorer",
          },
          items: [
            "analysts/development/data-explorer/data-profile",
            {
              type: "category",
              label: "Charts",
              link: {
                type: "doc",
                id: "analysts/development/data-explorer/charts/charts",
              },
              items: [
                "analysts/development/data-explorer/charts/area-chart",
                "analysts/development/data-explorer/charts/bar-chart",
                "analysts/development/data-explorer/charts/candlestick-chart",
                "analysts/development/data-explorer/charts/line-chart",
                "analysts/development/data-explorer/charts/map-chart",
                "analysts/development/data-explorer/charts/pie-chart",
                "analysts/development/data-explorer/charts/scatter-chart",
              ],
            },
          ],
        },
        {
          type: "category",
          label: "Functions",
          link: {
            type: "doc",
            id: "analysts/development/functions/functions",
          },
          items: [],
        },
        {
          type: "category",
          label: "Collaboration",
          link: {
            type: "doc",
            id: "analysts/development/collaboration/collaboration",
          },
          items: [
            "analysts/development/collaboration/collaboration-modes",
            "analysts/development/collaboration/canvas-annotations",
          ],
        },
        {
          type: "category",
          label: "Data tests",
          link: {
            type: "doc",
            id: "analysts/development/data-tests/data-tests",
          },
          items: [
            "analysts/development/data-tests/use-model-tests",
            "analysts/development/data-tests/use-project-tests",
          ],
        },
        "analysts/development/pipelines/logs",
        {
          type: "category",
          label: "Models",
          link: {
            type: "doc",
            id: "analysts/development/models/models",
          },
          items: [
            {
              type: "category",
              label: "Sources and targets",
              link: {
                type: "doc",
                id: "analysts/development/models/sources-target/sources-and-targets",
              },
              items: [
                {
                  type: "category",
                  label: "Platform-specific targets",
                  items: [
                    "analysts/development/models/target-platforms/databricks-target",
                    "analysts/development/models/target-platforms/bigquery-target",
                    "analysts/development/models/target-platforms/snowflake-target",
                  ],
                },
                "analysts/development/models/sources-target/dynamic-target-location",
                "analysts/development/models/sources-target/merge-approaches",
              ],
            },
            "analysts/development/models/configuration",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Versioning",
      link: {
        type: "doc",
        id: "analysts/version-control/version-control",
      },
      items: ["analysts/version-control/publication"],
    },
    "analysts/scheduling",
    "analysts/monitoring",
    {
      type: "category",
      label: "Extensibility",
      link: { type: "doc", id: "analysts/extensibility/extensibility" },
      items: [
        "analysts/extensibility/dependencies",
        "analysts/extensibility/sql-gem-builder",
      ],
    },
    {
      type: "category",
      label: "Prophecy Apps",
      link: { type: "doc", id: "analysts/business-apps/business-apps" },
      items: [
        "analysts/business-apps/run-apps",
        {
          type: "category",
          label: "App Builder",
          link: { type: "doc", id: "analysts/business-apps/app-builder" },
          items: [
            "analysts/business-apps/app-creation",
            "analysts/business-apps/app-components",
          ],
        },
      ],
    },

    ///------------------ ENGINEERS ------------------------///
    {
      type: "html",
      value: '<span class="sidebar-divider" />',
    },
    {
      type: "html",
      className: "sidebar-title",
      value: "Engineers",
      defaultStyle: true,
    },
    {
      type: "category",
      label: "Pipeline development",
      link: { type: "doc", id: "Spark/copilot-for-spark-users" },
      items: [
        {
          type: "category",
          label: "Pipelines",
          link: { type: "doc", id: "Spark/pipelines/pipelines" },
          items: [
            "Spark/pipelines/configuration",
            "Spark/pipelines/secrets-configs",
            "Spark/pipelines/pipeline-settings",
          ],
        },
        "Spark/dataset",
        {
          type: "category",
          label: "Gems",
          link: { type: "doc", id: "Spark/gems/spark-gems" },
          items: [
            {
              type: "category",
              label: "Source and Target",
              link: {
                type: "doc",
                id: "Spark/gems/source-target/source-target",
              },
              items: [
                {
                  type: "category",
                  label: "File",
                  items: [
                    "Spark/gems/source-target/file/avro",
                    "Spark/gems/source-target/file/csv",
                    "Spark/gems/source-target/file/data-generator",
                    "Spark/gems/source-target/file/delta",
                    "Spark/gems/source-target/file/fixed-format",
                    "Spark/gems/source-target/file/json",
                    "Spark/gems/source-target/file/kafka",
                    "Spark/gems/source-target/file/orc",
                    "Spark/gems/source-target/file/parquet",
                    "Spark/gems/source-target/file/seed",
                    "Spark/gems/source-target/file/text",
                    "Spark/gems/source-target/file/upload-file",
                    "Spark/gems/source-target/file/xlsx",
                    "Spark/gems/source-target/file/xml",
                  ],
                },
                {
                  type: "category",
                  label: "Catalog Table",
                  items: [
                    "Spark/gems/source-target/catalog-table/delta",
                    "Spark/gems/source-target/catalog-table/hive",
                    "Spark/gems/source-target/catalog-table/iceberg",
                  ],
                },
                {
                  type: "category",
                  label: "Warehouse",
                  items: [
                    "Spark/gems/source-target/warehouse/bigquery",
                    "Spark/gems/source-target/warehouse/cosmos",
                    "Spark/gems/source-target/warehouse/db2",
                    "Spark/gems/source-target/warehouse/jdbc",
                    "Spark/gems/source-target/warehouse/mongodb",
                    "Spark/gems/source-target/warehouse/oracle",
                    "Spark/gems/source-target/warehouse/redshift",
                    "Spark/gems/source-target/warehouse/snowflake",
                    "Spark/gems/source-target/warehouse/teradata",
                  ],
                },
                {
                  type: "category",
                  label: "Web Application",
                  items: [
                    "Spark/gems/source-target/web-apps/salesforce",
                    "Spark/gems/source-target/web-apps/smartsheet",
                  ],
                },
                "Spark/gems/source-target/lookup",
              ],
            },
            {
              type: "category",
              label: "Transform",
              link: {
                type: "doc",
                id: "Spark/gems/transform/transform",
              },
              items: [
                "Spark/gems/transform/aggregate",
                "Spark/gems/transform/bulk-column-expressions",
                "Spark/gems/transform/bulk-column-rename",
                "Spark/gems/transform/column-parser",
                "Spark/gems/transform/data-cleansing",
                "Spark/gems/transform/data-quality-check",
                "Spark/gems/transform/deduplicate",
                "Spark/gems/transform/dynamic-replace",
                "Spark/gems/transform/dynamic-select",
                "Spark/gems/transform/filter",
                "Spark/gems/transform/flatten-schema",
                "Spark/gems/transform/fuzzy-match",
                "Spark/gems/transform/limit",
                "Spark/gems/transform/order-by",
                "Spark/gems/transform/reformat",
                "Spark/gems/transform/sample-rows",
                "Spark/gems/transform/schema-transform",
                "Spark/gems/transform/set-operation",
                "Spark/gems/transform/unpivot",
                "Spark/gems/transform/window-function",
              ],
            },
            {
              type: "category",
              label: "Join/Split",
              link: {
                type: "doc",
                id: "Spark/gems/join-split/join-split",
              },
              items: [
                "Spark/gems/join-split/compare-columns",
                "Spark/gems/join-split/join",
                "Spark/gems/join-split/Repartition",
                "Spark/gems/join-split/row-distributor",
              ],
            },
            {
              type: "category",
              label: "Subgraph",
              link: {
                type: "doc",
                id: "Spark/gems/subgraph/subgraph",
              },
              items: [
                "Spark/gems/subgraph/basic-subgraph",
                "Spark/gems/subgraph/table-iterator",
                "Spark/gems/subgraph/while-iterator",
              ],
            },
            {
              type: "category",
              label: "Machine learning",
              link: {
                type: "doc",
                id: "Spark/gems/machine-learning/machine-learning",
              },
              items: [
                "Spark/gems/machine-learning/ml-openai",
                "Spark/gems/machine-learning/ml-pinecone-lookup",
                "Spark/gems/machine-learning/ml-text-processing",
                "Spark/gems/machine-learning/gen-ai-chatbot",
              ],
            },
            {
              type: "category",
              label: "Custom",
              link: {
                type: "doc",
                id: "Spark/gems/custom/custom",
              },
              items: [
                "Spark/gems/custom/script",
                "Spark/gems/custom/sql-statement",
                "Spark/gems/custom/delta-ops",
                "Spark/gems/custom/file-operations",
                "Spark/gems/custom/rest-api-enrich",
                "Spark/gems/custom/directory",
                "Spark/gems/custom/email",
                "Spark/gems/custom/email-data",
                "Spark/gems/custom/tableau",
              ],
            },
            "Spark/gems/expression-builder",
          ],
        },
        {
          type: "category",
          label: "Copilot",
          link: { type: "doc", id: "Spark/copilot/copilot-for-spark" },
          items: [],
        },
        {
          type: "category",
          label: "Execution",
          link: {
            type: "doc",
            id: "Spark/execution/execution",
          },
          items: [
            "Spark/execution/execution-metrics",
            "Spark/execution/data-sampling",
            "Spark/execution/conditional-execution",
          ],
        },
        {
          type: "category",
          label: "Data exploration",
          link: {
            type: "doc",
            id: "Spark/data-explorer/data-explorer",
          },
          items: ["Spark/data-explorer/data-profile"],
        },
        {
          type: "category",
          label: "Functions",
          items: [
            {
              type: "category",
              label: "Business rules engine",
              link: {
                type: "doc",
                id: "Spark/functions/business-rules-engine/business-rules-engine",
              },
              items: [],
            },
            "Spark/functions/udfs",
          ],
        },
        {
          type: "category",
          label: "Spark streaming",
          link: { type: "doc", id: "Spark/spark-streaming/streaming" },
          items: [
            {
              type: "category",
              label: "Streaming sources and targets",
              link: {
                type: "doc",
                id: "Spark/spark-streaming/streaming-sources-and-targets/streaming-sources-and-targets",
              },
              items: [
                "Spark/spark-streaming/streaming-sources-and-targets/streaming-file-apps",
                "Spark/spark-streaming/streaming-sources-and-targets/streaming-event-apps",
                "Spark/spark-streaming/streaming-sources-and-targets/streaming-warehouse-apps",
              ],
            },
            "Spark/spark-streaming/transformations-streaming",
          ],
        },
        "Spark/project-best-practices",
      ],
    },
    /// LINEAGE
    {
      type: "category",
      label: "Lineage",
      link: { type: "doc", id: "lineage/lineage" },
      items: ["lineage/lineage-extractor", "lineage/lineage-run-and-diagnose"],
    },
    /// CI-CD
    {
      type: "category",
      label: "CI/CD",
      link: { type: "doc", id: "ci-cd/reliable-ci-cd" },
      items: [
        {
          type: "category",
          label: "Git",
          link: { type: "doc", id: "ci-cd/git/Git" },
          items: [
            "ci-cd/git/git-workflow",
            "ci-cd/git/git-resolve",
            "ci-cd/git/pr-templates",
            "ci-cd/git/git-best-practices",
          ],
        },
        "ci-cd/tests",
        "ci-cd/data-diff",
        {
          type: "category",
          label: "Release and Deploy",
          link: { type: "doc", id: "ci-cd/deployment/Deployment" },
          items: [
            "ci-cd/deployment/deploy-project",
            "ci-cd/deployment/use-external-release-tags",
          ],
        },
        {
          type: "category",
          label: "Prophecy Build Tool (PBT)",
          link: {
            type: "doc",
            id: "ci-cd/prophecy-build-tool/prophecy-build-tool",
          },
          items: [
            "ci-cd/prophecy-build-tool/prophecy-build-tool-github-actions",
            "ci-cd/prophecy-build-tool/prophecy-build-tool-jenkins",
          ],
        },
      ],
    },
    /// ORCHESTRATION
    {
      type: "category",
      label: "Orchestration",
      link: { type: "doc", id: "Orchestration/Orchestration" },
      items: [
        {
          type: "category",
          label: "Pipeline monitoring",
          link: {
            type: "doc",
            id: "Orchestration/pipeline-monitoring/pipeline-monitoring",
          },
          items: [
            "Orchestration/pipeline-monitoring/enable-pipeline-monitoring",
            "Orchestration/pipeline-monitoring/use-pipeline-monitoring",
          ],
        },
        {
          type: "category",
          label: "Airflow",
          link: { type: "doc", id: "Orchestration/airflow/airflow" },
          items: ["Orchestration/airflow/airflow-tutorial-spark"],
        },
        "Orchestration/databricks-jobs",
        "Orchestration/multi-jobs-trigger",
      ],
    },
    /// EXTENSIBILITY
    {
      type: "category",
      label: "Extensibility",
      link: { type: "doc", id: "extensibility/extensibility" },
      items: [
        {
          type: "category",
          label: "Dependencies",
          link: { type: "doc", id: "extensibility/dependencies/dependencies" },
          items: [
            "extensibility/dependencies/spark-dependencies",
            "extensibility/dependencies/prophecy-libraries",
          ],
        },
        {
          type: "category",
          label: "Package Hub",
          link: { type: "doc", id: "extensibility/package-hub/package-hub" },
          items: [
            "extensibility/package-hub/template-hub",
            "extensibility/package-hub/use-imported-package",
          ],
        },
        {
          type: "category",
          label: "Gem Builder",
          items: [
            "extensibility/gem-builder/spark-gem-builder",
            "extensibility/gem-builder/gem-builder-reference",
            "extensibility/gem-builder/gem-builder-ui",
            "extensibility/gem-builder/optimization-functions",
          ],
        },
      ],
    },
  ],
  adminSidebar: [
    "administration/index",
    {
      type: "html",
      value: '<span class="sidebar-divider" />',
    },
    {
      type: "html",
      className: "sidebar-title",
      value: "Team Admins",
      defaultStyle: true,
    },
    {
      type: "category",
      label: "Teams and users",
      link: {
        type: "doc",
        id: "administration/teams-users/teams-users",
      },
      items: [
        "administration/teams-users/settings",
        "administration/teams-users/team-based-access",
      ],
    },
    {
      type: "category",
      label: "Project types",
      link: {
        type: "doc",
        id: "administration/project-types/project-types",
      },
      items: ["administration/project-types/project-creation-template"],
    },
    {
      type: "category",
      label: "Fabric setup",
      link: {
        type: "doc",
        id: "administration/fabrics",
      },
      items: [
        {
          type: "category",
          label: "Prophecy fabrics",
          link: {
            type: "doc",
            id: "administration/fabrics/prophecy-fabrics/prophecy-fabrics",
          },
          items: [
            {
              type: "category",
              label: "Connections",
              link: {
                type: "doc",
                id: "administration/fabrics/prophecy-fabrics/connections/connections",
              },
              items: [
                "administration/fabrics/prophecy-fabrics/connections/redshift",
                "administration/fabrics/prophecy-fabrics/connections/s3",
                "administration/fabrics/prophecy-fabrics/connections/databricks",
                "administration/fabrics/prophecy-fabrics/connections/onedrive",
                "administration/fabrics/prophecy-fabrics/connections/power-bi",
                "administration/fabrics/prophecy-fabrics/connections/sharepoint",
                "administration/fabrics/prophecy-fabrics/connections/mongodb",
                "administration/fabrics/prophecy-fabrics/connections/mssql",
                "administration/fabrics/prophecy-fabrics/connections/oracle",
                "administration/fabrics/prophecy-fabrics/connections/sftp",
                "administration/fabrics/prophecy-fabrics/connections/smartsheet",
                "administration/fabrics/prophecy-fabrics/connections/smtp",
                "administration/fabrics/prophecy-fabrics/connections/snowflake",
                "administration/fabrics/prophecy-fabrics/connections/tableau",
              ],
            },
          ],
        },
        {
          type: "category",
          label: "Spark fabrics",
          link: {
            type: "doc",
            id: "administration/fabrics/Spark-fabrics/Fabrics",
          },
          items: [
            {
              type: "category",
              label: "Databricks",
              link: {
                type: "doc",
                id: "administration/fabrics/Spark-fabrics/databricks/databricks",
              },
              items: [
                "administration/fabrics/Spark-fabrics/databricks/ucshared",
                "administration/fabrics/Spark-fabrics/databricks/databricks-policies",
                "administration/fabrics/Spark-fabrics/databricks/whitelist-plibs",
                "administration/fabrics/Spark-fabrics/databricks/volumes-plibs",
              ],
            },
            "administration/fabrics/Spark-fabrics/prophecy-managed-databricks",
            "administration/fabrics/Spark-fabrics/livy",
            "administration/fabrics/Spark-fabrics/emr",
            "administration/fabrics/Spark-fabrics/gcp-dataproc-fabric-guide",
            "administration/fabrics/Spark-fabrics/azure-synapse-fabric-guide",
          ],
        },
        {
          type: "category",
          label: "SQL fabrics",
          link: {
            type: "doc",
            id: "administration/fabrics/sql-fabrics/Fabrics",
          },
          items: [
            "administration/fabrics/sql-fabrics/databricks",
            "administration/fabrics/sql-fabrics/snowflake",
            "administration/fabrics/sql-fabrics/bigquery",
          ],
        },
        {
          type: "category",
          label: "Airflow fabrics",
          link: {
            type: "doc",
            id: "administration/fabrics/airflow-fabrics/airflow-fabrics",
          },
          items: [
            {
              type: "category",
              label: "Airflow connections",
              link: {
                type: "doc",
                id: "administration/fabrics/airflow-fabrics/connections/airflow_fabric_connections",
              },
              items: [
                "administration/fabrics/airflow-fabrics/connections/dbx_spark_connections",
                "administration/fabrics/airflow-fabrics/connections/dbx_sql_connections",
                "administration/fabrics/airflow-fabrics/connections/airflow_snowflake_connections",
                "administration/fabrics/airflow-fabrics/connections/aws-connection",
                "administration/fabrics/airflow-fabrics/connections/airflow_email_connections",
              ],
            },
            "administration/fabrics/airflow-fabrics/prophecy_managed_airflow_fabric",
            "administration/fabrics/airflow-fabrics/composer_fabric",
            "administration/fabrics/airflow-fabrics/MWAA_fabric",
            "administration/fabrics/airflow-fabrics/open-source-airflow",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Secrets",
      link: {
        type: "doc",
        id: "administration/secrets/secrets",
      },
      items: ["administration/secrets/secret-providers"],
    },
    {
      type: "html",
      value: '<span class="sidebar-divider" />',
    },
    {
      type: "html",
      className: "sidebar-title",
      value: "Prophecy Cluster Admins",
      defaultStyle: true,
    },
    "administration/architecture",
    "administration/prophecy-deployment",
    "administration/security",
    {
      type: "category",
      label: "Authentication",
      link: { type: "doc", id: "administration/authentication/authentication" },
      items: [
        {
          type: "autogenerated",
          dirName: "administration/authentication",
        },
      ],
    },
    {
      type: "category",
      label: "SaaS",
      items: [
        {
          type: "autogenerated",
          dirName: "administration/saas",
        },
      ],
    },
    {
      type: "category",
      label: "Self-hosted",
      link: { type: "doc", id: "administration/self-hosted/self-hosted" },
      items: [
        {
          type: "autogenerated",
          dirName: "administration/self-hosted",
        },
      ],
    },
    {
      type: "category",
      label: "Getting help",
      link: { type: "doc", id: "getting-help/getting-help" },
      items: [{ type: "autogenerated", dirName: "getting-help" }],
    },
  ],
  apiSidebar: ["api/index", "api/trigger-pipeline/trigger-pipeline-api"],
};

module.exports = sidebars;
