/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // defaultSidebar: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually
  gettingStartedSidebar: [
    "index",
    {
      type: "html",
      value: '<span class="sidebar-divider" />',
    },
    {
      type: "category",
      label: "Copilot",
      link: { type: "doc", id: "copilot/copilot" },
      items: [{ type: "autogenerated", dirName: "copilot" }],
    },
    {
      type: "category",
      label: "Concepts",
      items: [
        "getting-started/concepts/Fabric",
        "getting-started/concepts/project/projects",
        "getting-started/concepts/templates",
        "getting-started/concepts/pipelines",
        "getting-started/concepts/gems",
        "administration/teams-users/teams-users",
      ],
    },
    {
      type: "category",
      label: "Quick starts",
      link: {
        type: "doc",
        id: "getting-started/quick-starts/quick-starts",
      },
      items: [
        "getting-started/quick-starts/analysts-qs",
        "getting-started/quick-starts/engineers-qs",
        "getting-started/quick-starts/databricks-partner-connect",
      ],
    },
    "analysts/extensibility/template-hub",
    {
      type: "category",
      label: "Tutorials",
      link: {
        type: "doc",
        id: "getting-started/tutorials/tutorials",
      },
      items: [
        "getting-started/tutorials/sql-with-prophecy",
        "getting-started/tutorials/spark-with-databricks",
        "getting-started/tutorials/sql-with-snowflake",
      ],
    },
    {
      type: "html",
      value: '<span class="sidebar-divider" />',
    },
    {
      type: "html",
      className: "sidebar-title",
      value: "Editions",
      defaultStyle: true,
    },
    "getting-started/editions/prophecy-editions",
    "getting-started/editions/architecture",
    {
      type: "html",
      value: '<span class="sidebar-divider" />',
    },
    {
      type: "category",
      label: "Release notes",
      link: { type: "doc", id: "release_notes/release_notes" },
      items: [{ type: "autogenerated", dirName: "release_notes" }],
    },

    "administration/settings",
    {
      type: "category",
      label: "Access",
      items: [
        "administration/access/role-based-access",
        "administration/access/team-based-access",
      ],
    },
    {
      type: "category",
      label: "Getting help",
      link: { type: "doc", id: "getting-help/getting-help" },
      items: [{ type: "autogenerated", dirName: "getting-help" }],
    },
  ],
  /*---------------------------------- CORE ----------------------------------*/
  coreSidebar: [
    "analysts/index",
    {
      type: "html",
      value: '<span class="sidebar-divider" />',
    },
    {
      type: "category",
      label: "Pipeline development",
      link: { type: "doc", id: "analysts/development/development" },
      items: [
        {
          type: "category",
          label: "Pipelines",
          link: { type: "doc", id: "analysts/development/pipelines/pipelines" },
          items: [
            "analysts/development/pipelines/project-editor",
            "analysts/development/pipelines/pipeline-params",
            "analysts/development/pipelines/execution",
            "analysts/development/pipelines/logs",
            "analysts/development/pipelines/data-types",
          ],
        },
        {
          type: "category",
          label: "Gems",
          link: { type: "doc", id: "analysts/development/gems/gems" },
          items: [
            {
              type: "category",
              label: "Source and Target",
              link: {
                type: "doc",
                id: "analysts/development/gems/source-target/source-target",
              },
              items: [
                {
                  type: "category",
                  label: "Tables (Warehouse)",
                  link: {
                    type: "doc",
                    id: "analysts/development/gems/source-target/table/table",
                  },
                  items: [
                    "analysts/development/gems/source-target/table/databricks",
                    "analysts/development/gems/source-target/table/bigquery",
                    "analysts/development/gems/source-target/table/upload-files",
                  ],
                },
                {
                  type: "category",
                  label: "Tables (External systems)",
                  link: {
                    type: "doc",
                    id: "analysts/development/gems/source-target/external-table/table",
                  },
                  items: [
                    "analysts/development/gems/source-target/external-table/databricks",
                    "analysts/development/gems/source-target/external-table/bigquery",
                    "analysts/development/gems/source-target/external-table/synapse",
                    "analysts/development/gems/source-target/external-table/snowflake",
                    "analysts/development/gems/source-target/external-table/mssql",
                    "analysts/development/gems/source-target/external-table/mongodb",
                    "analysts/development/gems/source-target/external-table/oracle",
                    "analysts/development/gems/source-target/external-table/redshift",
                    "analysts/development/gems/source-target/external-table/salesforce",
                  ],
                },
                {
                  type: "category",
                  label: "File storage systems",
                  link: {
                    type: "doc",
                    id: "analysts/development/gems/source-target/file/file-storage",
                  },
                  items: [
                    {
                      type: "category",
                      label: "File types",
                      link: {
                        type: "doc",
                        id: "analysts/development/gems/source-target/file/file-types/file-types",
                      },
                      items: [
                        "analysts/development/gems/source-target/file/file-types/csv",
                        "analysts/development/gems/source-target/file/file-types/excel",
                        "analysts/development/gems/source-target/file/file-types/fixed-width",
                        "analysts/development/gems/source-target/file/file-types/json",
                        "analysts/development/gems/source-target/file/file-types/parquet",
                        "analysts/development/gems/source-target/file/file-types/xml",
                        "analysts/development/gems/source-target/file/file-types/text",
                      ],
                    },
                    "analysts/development/gems/source-target/file/s3-gem",
                    "analysts/development/gems/source-target/file/databricks-volumes-gem",
                    "analysts/development/gems/source-target/file/onedrive-gem",
                    "analysts/development/gems/source-target/file/sftp-gem",
                    "analysts/development/gems/source-target/file/sharepoint-gem",
                    "analysts/development/gems/source-target/file/smartsheet-gem",
                  ],
                },

                {
                  type: "category",
                  label: "Troubleshooting",
                  items: [
                    "analysts/development/gems/source-target/troubleshooting/multi-source-table",
                  ],
                },
              ],
            },
            {
              type: "category",
              label: "Transform",
              link: {
                type: "doc",
                id: "analysts/development/gems/transform/transform",
              },
              items: [
                "analysts/development/gems/transform/aggregate",
                "analysts/development/gems/transform/count-records",
                "analysts/development/gems/transform/dynamic-select",
                "analysts/development/gems/transform/fuzzy-match",
                "analysts/development/gems/transform/encode-decode",
                "analysts/development/gems/transform/pivot",
                "analysts/development/gems/transform/unpivot",
                "analysts/development/gems/transform/window",
              ],
            },
            {
              type: "category",
              label: "Prepare",
              link: {
                type: "doc",
                id: "analysts/development/gems/prepare/prepare",
              },
              items: [
                "analysts/development/gems/prepare/data-cleansing",
                "analysts/development/gems/prepare/data-masking",
                "analysts/development/gems/prepare/deduplicate",
                "analysts/development/gems/prepare/filter",
                "analysts/development/gems/prepare/find-duplicates",
                "analysts/development/gems/prepare/flatten-schema",
                "analysts/development/gems/prepare/limit",
                "analysts/development/gems/prepare/multi-column-rename",
                "analysts/development/gems/prepare/multi-column-edit",
                "analysts/development/gems/prepare/order-by",
                "analysts/development/gems/prepare/record-id",
                "analysts/development/gems/prepare/reformat",
              ],
            },
            {
              type: "category",
              label: "Join",
              link: {
                type: "doc",
                id: "analysts/development/gems/join-split/joins",
              },
              items: [
                "analysts/development/gems/join-split/join",
                "analysts/development/gems/join-split/union",
                "analysts/development/gems/join-split/union-by-name",
                "analysts/development/gems/join-split/intersect",
                "analysts/development/gems/join-split/except",
                "analysts/development/gems/join-split/dynamic-replace",
              ],
            },
            {
              type: "category",
              label: "Spatial",
              link: {
                type: "doc",
                id: "analysts/development/gems/spatial/spatial",
              },
              items: [
                "analysts/development/gems/spatial/buffer",
                "analysts/development/gems/spatial/create-point",
                "analysts/development/gems/spatial/distance",
                "analysts/development/gems/spatial/find-nearest",
                "analysts/development/gems/spatial/heatmap",
                "analysts/development/gems/spatial/polybuild",
                "analysts/development/gems/spatial/simplify",
                "analysts/development/gems/spatial/spatial-match",
              ],
            },
            {
              type: "category",
              label: "Parse",
              link: {
                type: "doc",
                id: "analysts/development/gems/parse/parse",
              },
              items: [
                "analysts/development/gems/parse/json-parse",
                "analysts/development/gems/parse/xml-parse",
                "analysts/development/gems/parse/text-to-column",
              ],
            },
            {
              type: "category",
              label: "Report",
              link: {
                type: "doc",
                id: "analysts/development/gems/report/report",
              },
              items: [
                "analysts/development/gems/report/email",
                "analysts/development/gems/report/power-bi",
                "analysts/development/gems/report/tableau",
              ],
            },
            "analysts/development/gems/subgraph/subgraph",
            {
              type: "category",
              label: "Custom",
              link: {
                type: "doc",
                id: "analysts/development/gems/custom/custom",
              },
              items: [
                "analysts/development/gems/custom/directory",
                "analysts/development/gems/custom/dynamic-input",
                "analysts/development/gems/custom/macro",
                "analysts/development/gems/custom/rest-api",
                "analysts/development/gems/custom/script",
                "analysts/development/gems/custom/stored-procedure",
                "analysts/development/gems/custom/sql-statement",
                "analysts/development/gems/custom/todo",
              ],
            },
            {
              type: "category",
              label: "Visual expressions",
              link: {
                type: "doc",
                id: "analysts/development/gems/visual-expression-builder/visual-expression-builder",
              },
              items: [
                "analysts/development/gems/visual-expression-builder/visual-expression-builder-reference",
                "analysts/development/gems/visual-expression-builder/use-the-expression-builder",
                "analysts/development/gems/visual-expression-builder/variant-data-type",
              ],
            },
          ],
        },

        {
          type: "category",
          label: "Agents and AI",
          link: {
            type: "doc",
            id: "analysts/development/ai-agent/ai-features",
          },
          items: [
            {
              type: "category",
              label: "Agent chat",
              link: {
                type: "doc",
                id: "analysts/development/ai-agent/ai-chat",
              },
              items: [
                "analysts/development/ai-agent/ai-explore",
                "analysts/development/ai-agent/ai-transform",
              ],
            },
            "analysts/development/copilot/expression-generation",
            "analysts/development/copilot/auto-documentation",
            "analysts/development/copilot/generate-fix",
          ],
        },
        "analysts/development/connections",
        {
          type: "category",
          label: "Data exploration",
          link: {
            type: "doc",
            id: "analysts/development/data-explorer/data-explorer",
          },
          items: [
            "analysts/development/data-explorer/data-profile",
            {
              type: "category",
              label: "Charts",
              link: {
                type: "doc",
                id: "analysts/development/data-explorer/charts/charts",
              },
              items: [
                "analysts/development/data-explorer/charts/area-chart",
                "analysts/development/data-explorer/charts/bar-chart",
                "analysts/development/data-explorer/charts/candlestick-chart",
                "analysts/development/data-explorer/charts/line-chart",
                "analysts/development/data-explorer/charts/map-chart",
                "analysts/development/data-explorer/charts/pie-chart",
                "analysts/development/data-explorer/charts/scatter-chart",
              ],
            },
          ],
        },
        {
          type: "category",
          label: "Data tests",
          link: {
            type: "doc",
            id: "analysts/development/data-tests/data-tests",
          },
          items: [
            "analysts/development/data-tests/use-model-tests",
            "analysts/development/data-tests/use-project-tests",
          ],
        },
        {
          type: "category",
          label: "Collaboration",
          link: {
            type: "doc",
            id: "analysts/development/collaboration/collaboration",
          },
          items: [
            "analysts/development/collaboration/collaboration-modes",
            "analysts/development/collaboration/canvas-annotations",
          ],
        },
        {
          type: "category",
          label: "Organization",
          items: [
            "analysts/development/organization/folders",
            "analysts/development/organization/containers",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Versioning",
      link: {
        type: "doc",
        id: "analysts/version-control/version-control",
      },
      items: [
        "analysts/version-control/publication",
        "analysts/version-control/migrate-managed",
        {
          type: "category",
          label: "Git",
          link: { type: "doc", id: "analysts/version-control/git/Git" },
          items: [
            "analysts/version-control/git/git-workflow",
            "analysts/version-control/git/git-resolve",
            "analysts/version-control/git/pr-templates",
            "analysts/version-control/git/git-best-practices",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Scheduling",
      link: { type: "doc", id: "analysts/scheduling/scheduling" },
      items: [
        "analysts/scheduling/schedule-setup",
        "analysts/scheduling/triggers",
        "analysts/scheduling/pipeline-trigger-gem",
        "analysts/scheduling/schedule-email-alerts",
      ],
    },
    "analysts/monitoring",
    {
      type: "html",
      value: '<span class="sidebar-divider" />',
    },
    {
      type: "category",
      label: "Extensibility",
      link: { type: "doc", id: "analysts/extensibility/extensibility" },
      items: [
        "analysts/extensibility/dependencies",

        {
          type: "category",
          label: "Functions",
          link: {
            type: "doc",
            id: "analysts/development/functions/functions",
          },
          items: [],
        },
        "analysts/extensibility/stored-procedure",
        {
          type: "category",
          label: "Gem building",
          items: [
            "analysts/extensibility/sql-gem-builder",
            "analysts/extensibility/gem-builder/spark-gem-builder",
            "analysts/extensibility/gem-builder/gem-builder-reference",
            "analysts/extensibility/gem-builder/gem-builder-ui",
            "analysts/extensibility/gem-builder/optimization-functions",
          ],
        },
      ],
    },
    "analysts/extensibility/package-hub",
    {
      type: "html",
      value: '<span class="sidebar-divider" />',
    },
    {
      type: "category",
      label: "Prophecy Apps",
      link: { type: "doc", id: "analysts/business-apps/business-apps" },
      items: [
        "analysts/business-apps/run-apps",
        {
          type: "category",
          label: "App Builder",
          link: { type: "doc", id: "analysts/business-apps/app-builder" },
          items: [
            "analysts/business-apps/app-creation",
            "analysts/business-apps/app-components",
            "analysts/business-apps/app-settings",
          ],
        },
      ],
    },
    {
      type: "html",
      value: '<span class="sidebar-divider" />',
    },
    {
      type: "category",
      label: "Fabric setup",
      link: {
        type: "doc",
        id: "analysts/prophecy-fabrics/prophecy-fabrics",
      },
      items: [
        {
          type: "category",
          label: "Connections",
          link: {
            type: "doc",
            id: "analysts/prophecy-fabrics/connections/connections",
          },
          items: [
            "analysts/prophecy-fabrics/connections/redshift",
            "analysts/prophecy-fabrics/connections/s3",
            "analysts/prophecy-fabrics/connections/synapse",
            "analysts/prophecy-fabrics/connections/databricks",
            "analysts/prophecy-fabrics/connections/bigquery",
            "analysts/prophecy-fabrics/connections/onedrive",
            "analysts/prophecy-fabrics/connections/power-bi",
            "analysts/prophecy-fabrics/connections/sharepoint",
            "analysts/prophecy-fabrics/connections/mongodb",
            "analysts/prophecy-fabrics/connections/mssql",
            "analysts/prophecy-fabrics/connections/oracle",
            "analysts/prophecy-fabrics/connections/salesforce",
            "analysts/prophecy-fabrics/connections/sftp",
            "analysts/prophecy-fabrics/connections/smartsheet",
            "analysts/prophecy-fabrics/connections/smtp",
            "analysts/prophecy-fabrics/connections/snowflake",
            "analysts/prophecy-fabrics/connections/tableau",
          ],
        },
      ],
    },
    /* ---------------------- ENTERPRISE ------------------------*/
  ],
  enterpriseSidebar: [
    "enterprise/index",
    {
      type: "html",
      value: '<span class="sidebar-divider" />',
    },
    {
      type: "category",
      label: "Pipeline development",
      link: { type: "doc", id: "enterprise/Spark/copilot-for-spark-users" },
      items: [
        {
          type: "category",
          label: "Pipelines",
          link: { type: "doc", id: "enterprise/Spark/pipelines/pipelines" },
          items: [
            "enterprise/Spark/pipelines/configuration",
            "enterprise/Spark/pipelines/secrets-configs",
            "enterprise/Spark/pipelines/pipeline-settings",
          ],
        },
        "enterprise/Spark/dataset",
        {
          type: "category",
          label: "Gems",
          link: { type: "doc", id: "enterprise/Spark/gems/spark-gems" },
          items: [
            {
              type: "category",
              label: "Source and Target",
              link: {
                type: "doc",
                id: "enterprise/Spark/gems/source-target/source-target",
              },
              items: [
                {
                  type: "category",
                  label: "File",
                  items: [
                    "enterprise/Spark/gems/source-target/file/avro",
                    "enterprise/Spark/gems/source-target/file/csv",
                    "enterprise/Spark/gems/source-target/file/data-generator",
                    "enterprise/Spark/gems/source-target/file/delta",
                    "enterprise/Spark/gems/source-target/file/fixed-format",
                    "enterprise/Spark/gems/source-target/file/json",
                    "enterprise/Spark/gems/source-target/file/kafka",
                    "enterprise/Spark/gems/source-target/file/orc",
                    "enterprise/Spark/gems/source-target/file/parquet",
                    "enterprise/Spark/gems/source-target/file/seed",
                    "enterprise/Spark/gems/source-target/file/text",
                    "enterprise/Spark/gems/source-target/file/upload-file",
                    "enterprise/Spark/gems/source-target/file/xlsx",
                    "enterprise/Spark/gems/source-target/file/xml",
                  ],
                },
                {
                  type: "category",
                  label: "Catalog Table",
                  items: [
                    "enterprise/Spark/gems/source-target/catalog-table/delta",
                    "enterprise/Spark/gems/source-target/catalog-table/hive",
                    "enterprise/Spark/gems/source-target/catalog-table/iceberg",
                  ],
                },
                {
                  type: "category",
                  label: "Warehouse",
                  items: [
                    "enterprise/Spark/gems/source-target/warehouse/bigquery",
                    "enterprise/Spark/gems/source-target/warehouse/cosmos",
                    "enterprise/Spark/gems/source-target/warehouse/db2",
                    "enterprise/Spark/gems/source-target/warehouse/jdbc",
                    "enterprise/Spark/gems/source-target/warehouse/mongodb",
                    "enterprise/Spark/gems/source-target/warehouse/oracle",
                    "enterprise/Spark/gems/source-target/warehouse/redshift",
                    "enterprise/Spark/gems/source-target/warehouse/snowflake",
                    "enterprise/Spark/gems/source-target/warehouse/teradata",
                  ],
                },
                {
                  type: "category",
                  label: "Web Application",
                  items: [
                    "enterprise/Spark/gems/source-target/web-apps/salesforce",
                    "enterprise/Spark/gems/source-target/web-apps/smartsheet",
                  ],
                },
                "enterprise/Spark/gems/source-target/lookup",
              ],
            },
            {
              type: "category",
              label: "Transform",
              link: {
                type: "doc",
                id: "enterprise/Spark/gems/transform/transform",
              },
              items: [
                "enterprise/Spark/gems/transform/aggregate",
                "enterprise/Spark/gems/transform/bulk-column-expressions",
                "enterprise/Spark/gems/transform/bulk-column-rename",
                "enterprise/Spark/gems/transform/column-parser",
                "enterprise/Spark/gems/transform/data-cleansing",
                "enterprise/Spark/gems/transform/data-quality-check",
                "enterprise/Spark/gems/transform/deduplicate",
                "enterprise/Spark/gems/transform/dynamic-replace",
                "enterprise/Spark/gems/transform/dynamic-select",
                "enterprise/Spark/gems/transform/filter",
                "enterprise/Spark/gems/transform/flatten-schema",
                "enterprise/Spark/gems/transform/fuzzy-match",
                "enterprise/Spark/gems/transform/limit",
                "enterprise/Spark/gems/transform/order-by",
                "enterprise/Spark/gems/transform/reformat",
                "enterprise/Spark/gems/transform/sample-rows",
                "enterprise/Spark/gems/transform/schema-transform",
                "enterprise/Spark/gems/transform/set-operation",
                "enterprise/Spark/gems/transform/unpivot",
                "enterprise/Spark/gems/transform/window-function",
              ],
            },
            {
              type: "category",
              label: "Join/Split",
              link: {
                type: "doc",
                id: "enterprise/Spark/gems/join-split/join-split",
              },
              items: [
                "enterprise/Spark/gems/join-split/compare-columns",
                "enterprise/Spark/gems/join-split/join",
                "enterprise/Spark/gems/join-split/Repartition",
                "enterprise/Spark/gems/join-split/row-distributor",
              ],
            },
            {
              type: "category",
              label: "Subgraph",
              link: {
                type: "doc",
                id: "enterprise/Spark/gems/subgraph/subgraph",
              },
              items: [
                "enterprise/Spark/gems/subgraph/basic-subgraph",
                "enterprise/Spark/gems/subgraph/table-iterator",
                "enterprise/Spark/gems/subgraph/while-iterator",
              ],
            },
            {
              type: "category",
              label: "Machine learning",
              link: {
                type: "doc",
                id: "enterprise/Spark/gems/machine-learning/machine-learning",
              },
              items: [
                "enterprise/Spark/gems/machine-learning/ml-openai",
                "enterprise/Spark/gems/machine-learning/ml-pinecone-lookup",
                "enterprise/Spark/gems/machine-learning/ml-text-processing",
                "enterprise/Spark/gems/machine-learning/gen-ai-chatbot",
              ],
            },
            {
              type: "category",
              label: "Custom",
              link: {
                type: "doc",
                id: "enterprise/Spark/gems/custom/custom",
              },
              items: [
                "enterprise/Spark/gems/custom/script",
                "enterprise/Spark/gems/custom/sql-statement",
                "enterprise/Spark/gems/custom/delta-ops",
                "enterprise/Spark/gems/custom/file-operations",
                "enterprise/Spark/gems/custom/rest-api-enrich",
                "enterprise/Spark/gems/custom/directory",
                "enterprise/Spark/gems/custom/email",
                "enterprise/Spark/gems/custom/email-data",
                "enterprise/Spark/gems/custom/tableau",
              ],
            },
            "enterprise/Spark/gems/expression-builder",
          ],
        },
        {
          type: "category",
          label: "Copilot",
          link: {
            type: "doc",
            id: "enterprise/Spark/copilot/copilot-for-spark",
          },
          items: [],
        },
        {
          type: "category",
          label: "Execution",
          link: {
            type: "doc",
            id: "enterprise/Spark/execution/execution",
          },
          items: [
            "enterprise/Spark/execution/execution-metrics",
            "enterprise/Spark/execution/data-sampling",
            "enterprise/Spark/execution/conditional-execution",
          ],
        },
        {
          type: "category",
          label: "Data exploration",
          link: {
            type: "doc",
            id: "enterprise/Spark/data-explorer/data-explorer",
          },
          items: ["enterprise/Spark/data-explorer/data-profile"],
        },
        {
          type: "category",
          label: "Functions",
          items: [
            {
              type: "category",
              label: "Business rules engine",
              link: {
                type: "doc",
                id: "enterprise/Spark/functions/business-rules-engine/business-rules-engine",
              },
              items: [],
            },
            "enterprise/Spark/functions/udfs",
          ],
        },
        {
          type: "category",
          label: "Spark streaming",
          link: {
            type: "doc",
            id: "enterprise/Spark/spark-streaming/streaming",
          },
          items: [
            {
              type: "category",
              label: "Streaming sources and targets",
              link: {
                type: "doc",
                id: "enterprise/Spark/spark-streaming/streaming-sources-and-targets/streaming-sources-and-targets",
              },
              items: [
                "enterprise/Spark/spark-streaming/streaming-sources-and-targets/streaming-file-apps",
                "enterprise/Spark/spark-streaming/streaming-sources-and-targets/streaming-event-apps",
                "enterprise/Spark/spark-streaming/streaming-sources-and-targets/streaming-warehouse-apps",
              ],
            },
            "enterprise/Spark/spark-streaming/transformations-streaming",
          ],
        },
        "enterprise/Spark/project-best-practices",
      ],
    },
    /// MODELING
    {
      type: "category",
      label: "Models",
      link: {
        type: "doc",
        id: "enterprise/models/models",
      },
      items: [
        {
          type: "category",
          label: "Sources and targets",
          link: {
            type: "doc",
            id: "enterprise/models/sources-target/sources-and-targets",
          },
          items: [
            {
              type: "category",
              label: "Platform-specific targets",
              items: [
                "enterprise/models/target-platforms/databricks-target",
                "enterprise/models/target-platforms/bigquery-target",
                "enterprise/models/target-platforms/snowflake-target",
              ],
            },
            "enterprise/models/sources-target/dynamic-target-location",
            "enterprise/models/sources-target/merge-approaches",
          ],
        },
        "enterprise/models/configuration",
      ],
    },
    /// LINEAGE
    {
      type: "category",
      label: "Lineage",
      link: { type: "doc", id: "enterprise/lineage/lineage" },
      items: [
        "enterprise/lineage/lineage-extractor",
        "enterprise/lineage/lineage-run-and-diagnose",
      ],
    },
    /// CI-CD
    {
      type: "category",
      label: "CI/CD",
      link: { type: "doc", id: "enterprise/ci-cd/reliable-ci-cd" },
      items: [
        "enterprise/ci-cd/tests",
        "enterprise/ci-cd/data-diff",
        {
          type: "category",
          label: "Release and Deploy",
          link: { type: "doc", id: "enterprise/ci-cd/deployment/Deployment" },
          items: [
            "enterprise/ci-cd/deployment/deploy-project",
            "enterprise/ci-cd/deployment/use-external-release-tags",
          ],
        },
        {
          type: "category",
          label: "Prophecy Build Tool (PBT)",
          link: {
            type: "doc",
            id: "enterprise/ci-cd/prophecy-build-tool/prophecy-build-tool",
          },
          items: [
            "enterprise/ci-cd/prophecy-build-tool/prophecy-build-tool-github-actions",
            "enterprise/ci-cd/prophecy-build-tool/prophecy-build-tool-jenkins",
          ],
        },
      ],
    },
    /// ORCHESTRATION
    {
      type: "category",
      label: "Orchestration",
      link: { type: "doc", id: "enterprise/Orchestration/Orchestration" },
      items: [
        {
          type: "category",
          label: "Pipeline monitoring",
          link: {
            type: "doc",
            id: "enterprise/Orchestration/pipeline-monitoring/pipeline-monitoring",
          },
          items: [
            "enterprise/Orchestration/pipeline-monitoring/enable-pipeline-monitoring",
            "enterprise/Orchestration/pipeline-monitoring/use-pipeline-monitoring",
          ],
        },
        "enterprise/Orchestration/databricks-jobs",
        "enterprise/Orchestration/alternative-schedulers",
        "enterprise/Orchestration/multi-jobs-trigger",
      ],
    },
    {
      type: "category",
      label: "Dependencies",
      link: { type: "doc", id: "enterprise/dependencies/dependencies" },
      items: [
        "enterprise/dependencies/spark-dependencies",
        "enterprise/dependencies/prophecy-libraries",
        "enterprise/package-hub/use-imported-package",
      ],
    },
    {
      type: "html",
      value: '<span class="sidebar-divider" />',
    },
    {
      type: "category",
      label: "Project types",
      link: {
        type: "doc",
        id: "administration/project-types/project-types",
      },
      items: ["administration/project-types/project-creation-template"],
    },
    {
      type: "category",
      label: "Fabric setup",
      link: {
        type: "doc",
        id: "enterprise/fabrics/fabrics",
      },
      items: [
        {
          type: "category",
          label: "Spark fabrics",
          link: {
            type: "doc",
            id: "enterprise/fabrics/Spark-fabrics/Fabrics",
          },
          items: [
            {
              type: "category",
              label: "Databricks",
              link: {
                type: "doc",
                id: "enterprise/fabrics/Spark-fabrics/databricks/databricks",
              },
              items: [
                "enterprise/fabrics/Spark-fabrics/databricks/databricks-serverless",
                "enterprise/fabrics/Spark-fabrics/databricks/ucshared",
                "enterprise/fabrics/Spark-fabrics/databricks/databricks-policies",
                "enterprise/fabrics/Spark-fabrics/databricks/whitelist-plibs",
                "enterprise/fabrics/Spark-fabrics/databricks/volumes-plibs",
              ],
            },
            "enterprise/fabrics/Spark-fabrics/prophecy-managed-databricks",
            "enterprise/fabrics/Spark-fabrics/livy",
            "enterprise/fabrics/Spark-fabrics/emr",
            "enterprise/fabrics/Spark-fabrics/gcp-dataproc-fabric-guide",
            "enterprise/fabrics/Spark-fabrics/azure-synapse-fabric-guide",
          ],
        },
        {
          type: "category",
          label: "SQL fabrics",
          link: {
            type: "doc",
            id: "enterprise/fabrics/sql-fabrics/Fabrics",
          },
          items: [
            "enterprise/fabrics/sql-fabrics/databricks",
            "enterprise/fabrics/sql-fabrics/snowflake",
            "enterprise/fabrics/sql-fabrics/bigquery",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Secrets",
      link: {
        type: "doc",
        id: "enterprise/fabrics/secrets/secrets",
      },
      items: ["enterprise/fabrics/secrets/secret-providers"],
    },
    {
      type: "html",
      value: '<span class="sidebar-divider" />',
    },

    "administration/prophecy-deployment",
    "administration/cluster-admin-settings",
    "administration/security",
    "administration/audit-logging",
    {
      type: "category",
      label: "Authentication",
      link: { type: "doc", id: "administration/authentication/authentication" },
      items: [
        {
          type: "autogenerated",
          dirName: "administration/authentication",
        },
      ],
    },
  ],
  apiSidebar: [
    "api/index",
    {
      type: "html",
      value: '<span class="sidebar-divider" />',
    },
    {
      type: "category",
      label: "Trigger Pipeline API",
      link: { type: "doc", id: "api/trigger-pipeline/trigger-pipeline-api" },
      items: ["api/trigger-pipeline/rest-api-gem-trigger"],
    },
  ],
};

module.exports = sidebars;
