/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // defaultSidebar: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually
  mySidebar: [
    "index",
    {
      type: "html",
      value: '<span class="sidebar-divider" />',
    },
    {
      type: "category",
      label: "Quick starts",
      collapsible: true,
      collapsed: true,
      link: { type: "doc", id: "getting-started/getting-started" },
      items: [{ type: "autogenerated", dirName: "getting-started" }],
    },
    {
      type: "category",
      label: "Concepts",
      collapsible: true,
      collapsed: true,
      link: { type: "doc", id: "concepts/key-concepts" },
      items: [{ type: "autogenerated", dirName: "concepts" }],
    },
    {
      type: "category",
      label: "Data Copilot",
      collapsible: true,
      collapsed: true,
      link: { type: "doc", id: "copilot/copilot" },
      items: [{ type: "autogenerated", dirName: "copilot" }],
    },
    {
      type: "category",
      label: "Release notes",
      collapsible: true,
      collapsed: true,
      link: { type: "doc", id: "release_notes/release_notes" },
      items: [{ type: "autogenerated", dirName: "release_notes" }],
    },
    {
      type: "html",
      value: '<span class="sidebar-divider" />',
    },
    {
      type: "category",
      label: "Spark",
      collapsible: true,
      collapsed: true,
      link: { type: "doc", id: "Spark/copilot-for-spark-users" },
      items: [{ type: "autogenerated", dirName: "Spark" }],
    },
    {
      type: "category",
      label: "SQL",
      collapsible: true,
      collapsed: true,
      link: { type: "doc", id: "SQL/copilot-for-sql-users" },
      items: [{ type: "autogenerated", dirName: "SQL" }],
    },
    {
      type: "category",
      label: "Lineage",
      collapsible: true,
      collapsed: true,
      link: { type: "doc", id: "lineage/lineage" },
      items: [{ type: "autogenerated", dirName: "lineage" }],
    },
    {
      type: "category",
      label: "Orchestration",
      collapsible: true,
      collapsed: true,
      link: { type: "doc", id: "Orchestration/Orchestration" },
      items: [{ type: "autogenerated", dirName: "Orchestration" }],
    },
    {
      type: "category",
      label: "Release and Deploy",
      collapsible: true,
      collapsed: true,
      link: { type: "doc", id: "deployment/Deployment" },
      items: [{ type: "autogenerated", dirName: "deployment" }],
    },
    {
      type: "category",
      label: "Package Hub",
      collapsible: true,
      collapsed: true,
      link: { type: "doc", id: "package-hub/package-hub" },
      items: [{ type: "autogenerated", dirName: "package-hub" }],
    },
    {
      type: "category",
      label: "Settings",
      collapsible: true,
      collapsed: true,
      link: { type: "doc", id: "settings/settings" },
      items: [{ type: "autogenerated", dirName: "settings" }],
    },
    {
      type: "html",
      value: '<span class="sidebar-divider" />',
    },
    {
      type: "category",
      label: "Getting help",
      collapsible: true,
      collapsed: true,
      link: { type: "doc", id: "getting-help/getting-help" },
      items: [{ type: "autogenerated", dirName: "getting-help" }],
    },
  ],
  adminSidebar: [
    "administration/index",
    "administration/prophecy-deployment",
    {
      type: "category",
      label: "Authentication",
      link: { type: "doc", id: "administration/authentication/authentication" },
      items: [
        {
          type: "autogenerated",
          dirName: "administration/authentication",
        },
      ],
    },
    {
      type: "category",
      label: "SaaS",
      items: [
        {
          type: "autogenerated",
          dirName: "administration/saas",
        },
      ],
    },
    {
      type: "category",
      label: "Self-hosted",
      link: { type: "doc", id: "administration/self-hosted/self-hosted" },
      items: [
        {
          type: "autogenerated",
          dirName: "administration/self-hosted",
        },
      ],
    },
    "administration/feature-matrix",
  ],
};

module.exports = sidebars;
