name: Cleanup PR Previews in Staging

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    name: Cleanup Staging PR Preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout staging repository
        uses: actions/checkout@v3
        with:
          repository: SimpleDataLabsInc/prophecy-docs-staging
          ref: gh-pages
          token: ${{ secrets.STAGING_DEPLOY_KEY }} # Use the deploy key with write access

      - name: Delete preview files
        run: |
          if git rm -r --ignore-unmatch preview/pr-${{ github.event.pull_request.number }}; then
            git commit -m "Remove preview for PR #${{ github.event.pull_request.number }}"
            git push origin gh-pages
          else
            echo "Preview directory preview/pr-${{ github.event.pull_request.number }} not found. Skipping cleanup."
          fi
        shell: bash

      - name: Report Cleanup Result
        if: always()
        run: |
          if [[ $? -eq 0 ]]; then
            echo "Successfully cleaned up preview for PR #${{ github.event.pull_request.number }}"
          else
            echo "Cleanup for PR #${{ github.event.pull_request.number }} failed or was skipped."
          fi
        shell: bash
