name: Deploy PR Preview to Staging

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  preview:
    name: Deploy PR Preview to Staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 23.x
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Set environment variables
        run: |
          echo "INKEEP_API_KEY=${{ secrets.INKEEP_API_KEY }}" >> $GITHUB_ENV
          echo "DOCS_URL=https://simpledatalabsinc.github.io/" >> $GITHUB_ENV
          echo "BASE_URL="/prophecy-docs-staging/preview/pr-${{ github.event.number }}/"" >> $GITHUB_ENV

      - name: Build website
        run: yarn install --frozen-lockfile && yarn build

      - name: Deploy PR Preview to Staging GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.STAGING_DEPLOY_KEY }}
          publish_dir: ./build
          destination_dir: preview/pr-${{ github.event.pull_request.number }}
          publish_branch: gh-pages
          external_repository: SimpleDataLabsInc/prophecy-docs-staging

      - name: Comment PR with preview link
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const previewUrl = `https://SimpleDataLabsInc.github.io/prophecy-docs-staging/preview/pr-${prNumber}/`;
            github.rest.issues.createComment({
              issue_number: prNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 Staging Preview available: [${previewUrl}](${previewUrl})`
            });
