name: Sync Inkeep Source

on:
  push:
    branches:
      - main

jobs:
  syncSourceJob:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Sync Source
        uses: inkeep/pr-commenter-action@v10
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          apiKey: ${{secrets.INKEEP_API_MGMT_KEY}}
          sourceId: "cm8x5dd0a00i3s601u6wu6ocb"
